cookie:
  expiry_days: 30
  key: super_secret_cookie_key
  name: sme_app_cookie

credentials:
  usernames:
    admin1:
      email: admin1@yourdomain.com
      name: Admin One
      password: Test123!
      roles:
        - admin
